### PR TITLE
Add Mixpanel analytics

### LINKED ISSUE #96: [FEATURE] Resource Analytics
**Describe your suggested improvement**
Add traffic analytics to the resources to track which resources are popular and less popular (and generally track activity on the site).

**Describe the benefit**
Allows for better measurement of the health of the site, its impact, and the impact of individual resources.

**Would you be capable/willing to implement the improvement?**
No. Enough on my plate at the moment, and this is outside my domain of expertise. Happy for someone else to take a look at this

**Additional comments**
Care needs to be taken with analytics provider. I've heard that Google Analytics doesn't respect privacy (although I'm not sure about the details). Good to dicsuss here first about which one we should use.

The analytics dashboards and raw data will be private to the Knowledge Hub moderators.

### PR DESCRIPTION
**Pull request by VeckoTheGecko**
## Describe your changes
Add mixpanel analytics to monitor traffic to:
- different pages in the website
- individual resources

This will allow us to monitor the engagement that the Knowledge Hub is having.

## Related issue number/link

Fixes #96

### CODE REVIEW

**Comment by VeckoTheGecko** [comment]
Perhaps its also an idea to add analytics to the tags in filter box 🤔

**Comment by dmlb** [comment]
> Perhaps its also an idea to add analytics to the tags in filter box 🤔

Or search terms to learn synonyms or missing resources 🧐

**Review by dmlb — APPROVED** [review]

**Comment by VeckoTheGecko** [comment]
> Or search terms to learn synonyms or missing resources 🧐

Great idea! I'll look to make these changes in the next couple days 🕺

**Comment by VeckoTheGecko** [comment]
Good to go! Just a note that analytics won't always be 100% acurate (due to users using privacy focused browsers/blockers etc).

**Comment by dmlb** [comment]
> @dmlb , do you have any idea what the best practice is re. introducing analytics? Should we add a disclaimer in the website somewhere that we're collecting data? Perhaps here? image
> 
> > Data Disclaimer: By using this website, you consent to the collection of usage data, including clicks on "resources", search terms used, and pages visited. This data is solely used to monitor site usage, and to enhance the reach of the project. As this project is open source, you can inspect the usage of analytics. Our analytics platform is Mixpanel, with data being stored in the EU.

probably good to link back to their privacy agreement https://mixpanel.com/legal/privacy-policy

**Comment by VeckoTheGecko** [comment]
Great idea @dmlb ! Done now in #352

**Pull request merged**
